### ISSUE TITLE
Dynamics Layout Problem

### ISSUE THREAD

**Issue by cagrd** [MicrosoftDocs/dynamics-365-mixed-reality#19]
Hello, I have hololens1. I'm using the Layout application, but the 3D object looks red. The colors in the import tool are smooth. What is the reason? I could share a video if you wish. My mail is cdinc@datamarket.com.tr

---
#### Belge Ayrıntıları

⚠ *Bu bölümü düzenlemeyin. docs.microsoft.com ➟ GitHub sorunu bağlantısı için gereklidir.*

* ID: 6f4f2cb6-e5ce-2472-cd0c-3369baeb6982
* Version Independent ID: 47ea4565-d19c-232b-947c-d4fd5f2955ce
* Content: [Overview of Dynamics 365 Import Tool (Preview) - Dynamics 365 Mixed Reality](https://docs.microsoft.com/tr-tr/dynamics365/mixed-reality/import-tool/index#feedback)
* Content Source: [mr-docs/import-tool/index.md](https://github.com/MicrosoftDocs/dynamics-365-mixed-reality/blob/master/mr-docs/import-tool/index.md)
* Service: **crm-online**
* GitHub Login: @JBrentJ
* Microsoft Alias: **v-jerja**

**Comment by JBrentJ** [comment]
Hi Belge,
I am sorry to hear that you are having this issue.  Is it possible that you are operating Layout in "Performance mode"?  This applies a single material color to each mesh instead of showing materials.  This can increase performance when you have multiple objects in the scene.
To turn it off do the following:
From inside the Layout application navigate to "Settings" -> "Performance" and then select "turn off single color"
This should turn off performance mode and return your model to its original state.

Best,
Brent
