### ISSUE TITLE
Missing "mailbox enabled" requirement for using One Time Call

### ISSUE THREAD

**Issue by mabrizi01** [MicrosoftDocs/dynamics-365-mixed-reality#58]
Just helped a customer in a tricky issue that probably is worth to be highlighted.
 
A full licensed user for Remote Assist (Common Data Service for Remote Assist, Dynamics 365 Remote Assist, Microsoft Teams), if not owning any license enabling him for mail feature, cannot generate a One Time Call. This is due to the fact that doing so, he should add a meeting into his calendar but he doesn't have it! The calendar in fact is enabled only when a user is mailbox enabled.

I think that this situation should be taken in serious consideration because it could present a commercial side-effect on Remote Assist proposal.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e312080c-4d3c-d30c-91cb-2b3906d50e01
* Version Independent ID: 44fb8bd5-fe16-b37a-6329-522cec1200c8
* Content: [Invite a user to join a one-time call (public preview) in Microsoft Dynamics 365 Remote Assist - Dynamics 365 Mixed Reality](https://docs.microsoft.com/en-us/dynamics365/mixed-reality/remote-assist/one-time-call)
* Content Source: [mr-docs/remote-assist/one-time-call.md](https://github.com/MicrosoftDocs/dynamics-365-mixed-reality/blob/main/mr-docs/remote-assist/one-time-call.md)
* Service: **crm-online**
* GitHub Login: @BryceHolmes
* Microsoft Alias: **soanigbo**

**Comment by BryceHolmes** [comment]
+ Alex. Alex, thoughts on this and anything we need to add to the docs?

From: Marco Brizi ***@***.***>
Sent: Friday, May 14, 2021 9:17 AM
To: MicrosoftDocs/dynamics-365-mixed-reality ***@***.***>
Cc: Bryce Holmes (Aquent LLC) ***@***.***>; Mention ***@***.***>
Subject: [MicrosoftDocs/dynamics-365-mixed-reality] Missing "mailbox enabled" requirement for using One Time Call (#58)


Just helped a customer in a tricky issue that probably is worth to be highlighted.

A full licensed user for Remote Assist (Common Data Service for Remote Assist, Dynamics 365 Remote Assist, Microsoft Teams), if not owning any license enabling him for mail feature, cannot generate a One Time Call. This is due to the fact that doing so, he should add a meeting into his calendar but he doesn't have it! The calendar in fact is enabled only when a user is mailbox enabled.

I think that this situation should be taken in serious consideration because it could present a commercial side-effect on Remote Assist proposal.

________________________________
Document Details

⚠ Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.

  *   ID: e312080c-4d3c-d30c-91cb-2b3906d50e01
  *   Version Independent ID: 44fb8bd5-fe16-b37a-6329-522cec1200c8
  *   Content: Invite a user to join a one-time call (public preview) in Microsoft Dynamics 365 Remote Assist - Dynamics 365 Mixed Reality<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fdynamics365%2Fmixed-reality%2Fremote-assist%2Fone-time-call&data=04%7C01%7Cv-bholmes%40microsoft.com%7Cef404200aa6a41acffa208d916f3bba1%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637566058343798763%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=hxM1Xpxz7zXmYFs9fYMqEjvuRwsZjOUQrD0ZyErjdYw%3D&reserved=0>
  *   Content Source: mr-docs/remote-assist/one-time-call.md<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fdynamics-365-mixed-reality%2Fblob%2Fmain%2Fmr-docs%2Fremote-assist%2Fone-time-call.md&data=04%7C01%7Cv-bholmes%40microsoft.com%7Cef404200aa6a41acffa208d916f3bba1%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637566058343808756%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Br20oi7FtAnCOL1GKSuLQRQ8Lhrdm%2BceRkPiG78PDQQ%3D&reserved=0>
  *   Service: crm-online
  *   GitHub Login: @BryceHolmes<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FBryceHolmes&data=04%7C01%7Cv-bholmes%40microsoft.com%7Cef404200aa6a41acffa208d916f3bba1%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637566058343818748%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=0%2BkwGpJTpre0VXCQpRBV7oRN0SmVVb2jSwoBSdIQKJ8%3D&reserved=0>
  *   Microsoft Alias: soanigbo

**Comment by v-wendysmith** [comment]
@mabrizi01 I'm a new writer to the Mixed Reality team so apologies that a response has not been provided. Your request is now in the documentation. See see the 2nd table with Exchange Online here: [https://learn.microsoft.com/en-us/dynamics365/mixed-reality/remote-assist/requirements#dynamics-365-remote-assist-app-user]. Thank you!
