### ISSUE TITLE
Could you please provide the support of QR Code tracking support for Android and iOS devices.

### ISSUE THREAD

**Issue by ajinkya446** [MicrosoftDocs/dynamics-365-mixed-reality#63]
**Actual Problem:**

While working with mobile platforms using Mixed Reality and ARFoundation in Flutter AR Application for both Android and iOS platforms, I wanted to align the BIM model in real world using QR code tracking. But there are some limitations for Android and iOS devices, that there is no support for QR code tracking as per mentioned in the documentation. Kindly check below links and images

https://docs.microsoft.com/en-us/wi...atform-capabilities-and-apis/qr-code-tracking

![image](https://user-images.githubusercontent.com/49361315/128309888-30c4cb4a-2f86-4ec2-9df4-d28d7db48fb6.png)

**Platforms:**
Android : 8.0 and above
iOS : 13.0 and above
Unity Editor : 2019.4.22
Flutter : 2.2.3

**Expected Behavior:**
So could you please provide the same QR code tracking feature for Android and iOS devices as well.

**Comment by khodenikhil22** [comment]
I need to have same support for the mobility platform to work with AR application of Flutter-Unity integration. Can you please provide the support ?

**Comment by khodenikhil22** [comment]
**Actual Problem :**
I'm working on AR application with the support of Flutter-Unity integration. In which i wanted to get real world anchor by tracking the QR code. So while working on it, i noticed that there is no support for the "QR Tracking" feature for the mobility platforms. I found only "Hololens 2" and "Immersive Device" support for this feature.

**Platforms:**
- Unity Editor 2019.4.15f
- Flutter 2.2.3
- Android 8.0 and above
- iOS 13.0 and above

**Expected Behaviour:**
I need to have same support for the mobility platform to work with AR application of Flutter-Unity integration. Could you please provide the support of this feature ?

**Comment by m-hartmann** [comment]
Hallo Ajinkya @ajinkya446 

Thank you for reaching out and apologies for the delay to reply. I recently took over Dynamics 365 MR docs. The article you refer to is from the Windows Mixed Reality team. This documentation repo is for Dynamics 365 mixed reality apps like Guides and Remote Assist. If you want to provide feedback and request a feature from the Windows MR team, [please refer to this article.](https://learn.microsoft.com/hololens/hololens-feedback).

I'm closing this issue in our repo but feel free to reopen or create a new one if I misinterpreted your feedback. 

Thanks, 
Michael
