### ISSUE TITLE
Sandbox option not mentioned here

### ISSUE THREAD

**Issue by fmarcellino** [MicrosoftDocs/dynamics-365-mixed-reality#83]
The following page shows that we can have at least two Dataverse environments on a Guides deployment, test and production - https://learn.microsoft.com/en-us/dynamics365/mixed-reality/guides/admin-deployment-playbook#test-vs-production-environments.

However, this doc is not mentioning the sandbox option.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7c1e4a90-4d80-f2d7-22f8-3eb485eaefd2
* Version Independent ID: 0498517c-853e-af4a-cae3-011101b68ea8
* Content: [Install the Dynamics 365 Guides solution - Dynamics 365 Mixed Reality](https://learn.microsoft.com/en-us/dynamics365/mixed-reality/guides/setup-step-two)
* Content Source: [mr-docs/guides/setup-step-two.md](https://github.com/MicrosoftDocs/dynamics-365-mixed-reality/blob/main/mr-docs/guides/setup-step-two.md)
* Service: **dynamics-365-guides**
* GitHub Login: @Mamaylya
* Microsoft Alias: **mamaylya**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @fmarcellino. This issue has been assigned to the doc author for review.

**Comment by v-wendysmith** [comment]
Hello @fmarcellino. Thank you for your feedback!  The playbook is using “Production” and “Test” to mean the purpose of the environment in the customer operations/workflow, not the actual selections as an **Environment Type** from a Dynamics admin perspective. Since that isn't clear, I will update the doc to indicate a "Test" or "Sandbox" environment. I hope that helps. Thank you.

**Comment by v-wendysmith** [comment]
Doc updated.
